project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!VizCodes.qmd"

website:
  title: "Mark G Scott"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - href: DataVisualization.qmd
        text: Data Exploration
      - href: contactme.qmd
        text: Contact Me
    tools:
      - icon: linkedin
        text: Linkedin
        href: https://www.linkedin.com/in/mark-scott-bb6ab4329/?isSelfProfile=true
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2025, Mark G Scott"

format:
  html:
    theme: journal
    css: styles.css
    toc: true
    toc-depth: 1
    link-external-newwindow: true

editor: source
